/* ============================================================================
 * Family Hub — configuration
 *
 * Paste your Supabase Project URL and anon public key below.
 *
 * The anon key is MEANT to be public — it ships in every browser that loads
 * this page, and that is how Supabase is designed to work. Security comes from
 * the Row Level Security policies in supabase/schema.sql, never from hiding
 * this value. NEVER put the service_role key in this file.
 *
 * Until these are filled in, the app runs in DEMO MODE with sample data so you
 * can open index.html straight off your desktop and click around.
 * ==========================================================================*/
export const CONFIG = {
  SUPABASE_URL:  'https://rauvytdltnbqrvyiornh.supabase.co',
  SUPABASE_ANON: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdXZ5dGRsdG5icXJ2eWlvcm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxODAzMzksImV4cCI6MjEwMjc1NjMzOX0.EN7nf6O3eo7LRuepdwlSHWKlliEPOxfIhW0C1SOEIU0',

  HOUSEHOLD_ID: '00000000-0000-0000-0000-000000000001',
  TIMEZONE:     'America/Chicago',

  // Web Push public key — generated by vapid-keys.html and verified to match the
  // private key held in Supabase secrets. If you ever regenerate, you MUST replace
  // both halves together; a mismatched pair fails silently with no error anywhere.
  // The private key never belongs in this file.
  VAPID_PUBLIC: 'BEzeeOkIvPyjjqqLHPz1wuCJ97CllJ-dClSm96qFvhpgrafIUWEPEvbRPeSgqtQdEU2spiMUEzAYV_mUnsjvcBg',

  // Flip to true once A2P 10DLC registration clears and the Twilio secrets
  // are set in Supabase. Nothing else in the app changes.
  SMS_ENABLED: false
};

export const isDemo = () =>
  CONFIG.SUPABASE_URL.includes('PASTE') || CONFIG.SUPABASE_ANON.includes('PASTE');
